// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqervcquolnbodwhbwqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZXJ2Y3F1b2xuYm9kd2hid3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODA0NjEsImV4cCI6MjA2NDc1NjQ2MX0.BHUx3gwE8yWGOjd1RO3zuY_Uj2HiuOsFbZ97lLyy_mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);